replicaCount: 2

image:
  repository: ghcr.io/gaev-tech/api-tracker/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: true
  host: apitracker.ru
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    secretName: frontend-tls

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
