// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: workspace/v1/workspace.proto

package workspacev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceService_GetTaskRights_FullMethodName     = "/workspace.v1.WorkspaceService/GetTaskRights"
	WorkspaceService_GetProjectMembers_FullMethodName = "/workspace.v1.WorkspaceService/GetProjectMembers"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspaceService is called by automations-service.
type WorkspaceServiceClient interface {
	// GetTaskRights returns the effective rights bitmask for a user on a task.
	// Called by automations-service to evaluate RSQL conditions against task access.
	GetTaskRights(ctx context.Context, in *GetTaskRightsRequest, opts ...grpc.CallOption) (*GetTaskRightsResponse, error)
	// GetProjectMembers returns all members of a project with their roles.
	// Called by automations-service to resolve project membership.
	GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) GetTaskRights(ctx context.Context, in *GetTaskRightsRequest, opts ...grpc.CallOption) (*GetTaskRightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskRightsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetTaskRights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectMembersResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetProjectMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations must embed UnimplementedWorkspaceServiceServer
// for forward compatibility.
//
// WorkspaceService is called by automations-service.
type WorkspaceServiceServer interface {
	// GetTaskRights returns the effective rights bitmask for a user on a task.
	// Called by automations-service to evaluate RSQL conditions against task access.
	GetTaskRights(context.Context, *GetTaskRightsRequest) (*GetTaskRightsResponse, error)
	// GetProjectMembers returns all members of a project with their roles.
	// Called by automations-service to resolve project membership.
	GetProjectMembers(context.Context, *GetProjectMembersRequest) (*GetProjectMembersResponse, error)
	mustEmbedUnimplementedWorkspaceServiceServer()
}

// UnimplementedWorkspaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceServiceServer struct{}

func (UnimplementedWorkspaceServiceServer) GetTaskRights(context.Context, *GetTaskRightsRequest) (*GetTaskRightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskRights not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetProjectMembers(context.Context, *GetProjectMembersRequest) (*GetProjectMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectMembers not implemented")
}
func (UnimplementedWorkspaceServiceServer) mustEmbedUnimplementedWorkspaceServiceServer() {}
func (UnimplementedWorkspaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_GetTaskRights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetTaskRights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetTaskRights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetTaskRights(ctx, req.(*GetTaskRightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetProjectMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetProjectMembers(ctx, req.(*GetProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskRights",
			Handler:    _WorkspaceService_GetTaskRights_Handler,
		},
		{
			MethodName: "GetProjectMembers",
			Handler:    _WorkspaceService_GetProjectMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace/v1/workspace.proto",
}
