// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/workspace.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRightsRequest) Reset() {
	*x = GetTaskRightsRequest{}
	mi := &file_workspace_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRightsRequest) ProtoMessage() {}

func (x *GetTaskRightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRightsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRightsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTaskRightsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskRightsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rights is a bitmask of R-1..R-14 as defined in the access model.
	// Bit N-1 corresponds to right R-N (e.g. bit 0 = R-1, bit 13 = R-14).
	Rights        uint32 `protobuf:"varint,1,opt,name=rights,proto3" json:"rights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRightsResponse) Reset() {
	*x = GetTaskRightsResponse{}
	mi := &file_workspace_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRightsResponse) ProtoMessage() {}

func (x *GetTaskRightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRightsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskRightsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskRightsResponse) GetRights() uint32 {
	if x != nil {
		return x.Rights
	}
	return 0
}

type GetProjectMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMembersRequest) Reset() {
	*x = GetProjectMembersRequest{}
	mi := &file_workspace_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMembersRequest) ProtoMessage() {}

func (x *GetProjectMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMembersRequest.ProtoReflect.Descriptor instead.
func (*GetProjectMembersRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectMembersRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ProjectMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMembersResponse) Reset() {
	*x = GetProjectMembersResponse{}
	mi := &file_workspace_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMembersResponse) ProtoMessage() {}

func (x *GetProjectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMembersResponse.ProtoReflect.Descriptor instead.
func (*GetProjectMembersResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectMembersResponse) GetMembers() []*ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProjectMember struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// role is the member's role in the project (e.g. "owner", "admin", "member").
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_workspace_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_workspace_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_workspace_v1_workspace_proto protoreflect.FileDescriptor

const file_workspace_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x1cworkspace/v1/workspace.proto\x12\fworkspace.v1\"H\n" +
	"\x14GetTaskRightsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"/\n" +
	"\x15GetTaskRightsResponse\x12\x16\n" +
	"\x06rights\x18\x01 \x01(\rR\x06rights\"9\n" +
	"\x18GetProjectMembersRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"R\n" +
	"\x19GetProjectMembersResponse\x125\n" +
	"\amembers\x18\x01 \x03(\v2\x1b.workspace.v1.ProjectMemberR\amembers\"<\n" +
	"\rProjectMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role2\xd2\x01\n" +
	"\x10WorkspaceService\x12X\n" +
	"\rGetTaskRights\x12\".workspace.v1.GetTaskRightsRequest\x1a#.workspace.v1.GetTaskRightsResponse\x12d\n" +
	"\x11GetProjectMembers\x12&.workspace.v1.GetProjectMembersRequest\x1a'.workspace.v1.GetProjectMembersResponseBLZJgithub.com/gaev-tech/api-tracker/contracts/proto/workspace/gen;workspacev1b\x06proto3"

var (
	file_workspace_v1_workspace_proto_rawDescOnce sync.Once
	file_workspace_v1_workspace_proto_rawDescData []byte
)

func file_workspace_v1_workspace_proto_rawDescGZIP() []byte {
	file_workspace_v1_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_workspace_proto_rawDesc), len(file_workspace_v1_workspace_proto_rawDesc)))
	})
	return file_workspace_v1_workspace_proto_rawDescData
}

var file_workspace_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workspace_v1_workspace_proto_goTypes = []any{
	(*GetTaskRightsRequest)(nil),      // 0: workspace.v1.GetTaskRightsRequest
	(*GetTaskRightsResponse)(nil),     // 1: workspace.v1.GetTaskRightsResponse
	(*GetProjectMembersRequest)(nil),  // 2: workspace.v1.GetProjectMembersRequest
	(*GetProjectMembersResponse)(nil), // 3: workspace.v1.GetProjectMembersResponse
	(*ProjectMember)(nil),             // 4: workspace.v1.ProjectMember
}
var file_workspace_v1_workspace_proto_depIdxs = []int32{
	4, // 0: workspace.v1.GetProjectMembersResponse.members:type_name -> workspace.v1.ProjectMember
	0, // 1: workspace.v1.WorkspaceService.GetTaskRights:input_type -> workspace.v1.GetTaskRightsRequest
	2, // 2: workspace.v1.WorkspaceService.GetProjectMembers:input_type -> workspace.v1.GetProjectMembersRequest
	1, // 3: workspace.v1.WorkspaceService.GetTaskRights:output_type -> workspace.v1.GetTaskRightsResponse
	3, // 4: workspace.v1.WorkspaceService.GetProjectMembers:output_type -> workspace.v1.GetProjectMembersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workspace_v1_workspace_proto_init() }
func file_workspace_v1_workspace_proto_init() {
	if File_workspace_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_workspace_proto_rawDesc), len(file_workspace_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_v1_workspace_proto_depIdxs,
		MessageInfos:      file_workspace_v1_workspace_proto_msgTypes,
	}.Build()
	File_workspace_v1_workspace_proto = out.File
	file_workspace_v1_workspace_proto_goTypes = nil
	file_workspace_v1_workspace_proto_depIdxs = nil
}
