// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityType mirrors the entity types tracked in usage_counters.
type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_TYPE_TASK        EntityType = 1
	EntityType_ENTITY_TYPE_PROJECT     EntityType = 2
	EntityType_ENTITY_TYPE_TEAM        EntityType = 3
	EntityType_ENTITY_TYPE_AUTOMATION  EntityType = 4
	EntityType_ENTITY_TYPE_MEMBER      EntityType = 5
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_TASK",
		2: "ENTITY_TYPE_PROJECT",
		3: "ENTITY_TYPE_TEAM",
		4: "ENTITY_TYPE_AUTOMATION",
		5: "ENTITY_TYPE_MEMBER",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"ENTITY_TYPE_TASK":        1,
		"ENTITY_TYPE_PROJECT":     2,
		"ENTITY_TYPE_TEAM":        3,
		"ENTITY_TYPE_AUTOMATION":  4,
		"ENTITY_TYPE_MEMBER":      5,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_v1_billing_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_billing_v1_billing_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

type CheckLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityType    EntityType             `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=billing.v1.EntityType" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitRequest) Reset() {
	*x = CheckLimitRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitRequest) ProtoMessage() {}

func (x *CheckLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckLimitRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLimitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckLimitRequest) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

type CheckLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitResponse) Reset() {
	*x = CheckLimitResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitResponse) ProtoMessage() {}

func (x *CheckLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckLimitResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_billing_v1_billing_proto protoreflect.FileDescriptor

const file_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/billing.proto\x12\n" +
	"billing.v1\"e\n" +
	"\x11CheckLimitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x16.billing.v1.EntityTypeR\n" +
	"entityType\".\n" +
	"\x12CheckLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed*\xa2\x01\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTITY_TYPE_TASK\x10\x01\x12\x17\n" +
	"\x13ENTITY_TYPE_PROJECT\x10\x02\x12\x14\n" +
	"\x10ENTITY_TYPE_TEAM\x10\x03\x12\x1a\n" +
	"\x16ENTITY_TYPE_AUTOMATION\x10\x04\x12\x16\n" +
	"\x12ENTITY_TYPE_MEMBER\x10\x052]\n" +
	"\x0eBillingService\x12K\n" +
	"\n" +
	"CheckLimit\x12\x1d.billing.v1.CheckLimitRequest\x1a\x1e.billing.v1.CheckLimitResponseBHZFgithub.com/gaev-tech/api-tracker/contracts/proto/billing/gen;billingv1b\x06proto3"

var (
	file_billing_v1_billing_proto_rawDescOnce sync.Once
	file_billing_v1_billing_proto_rawDescData []byte
)

func file_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)))
	})
	return file_billing_v1_billing_proto_rawDescData
}

var file_billing_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_v1_billing_proto_goTypes = []any{
	(EntityType)(0),            // 0: billing.v1.EntityType
	(*CheckLimitRequest)(nil),  // 1: billing.v1.CheckLimitRequest
	(*CheckLimitResponse)(nil), // 2: billing.v1.CheckLimitResponse
}
var file_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: billing.v1.CheckLimitRequest.entity_type:type_name -> billing.v1.EntityType
	1, // 1: billing.v1.BillingService.CheckLimit:input_type -> billing.v1.CheckLimitRequest
	2, // 2: billing.v1.BillingService.CheckLimit:output_type -> billing.v1.CheckLimitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_billing_v1_billing_proto_init() }
func file_billing_v1_billing_proto_init() {
	if File_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_billing_v1_billing_proto_depIdxs,
		EnumInfos:         file_billing_v1_billing_proto_enumTypes,
		MessageInfos:      file_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_billing_v1_billing_proto = out.File
	file_billing_v1_billing_proto_goTypes = nil
	file_billing_v1_billing_proto_depIdxs = nil
}
